import Head from 'next/head'
import React, { useCallback } from 'react'

import Layout from "../components/layout";
import FileUpload from '../components/fileUpload';





export default function Home() {

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" h-screen ">

        <FileUpload />

      </div>




    </Layout>



  )
}
