import Head from "next/head";
import React, { useCallback, useContext } from "react";
import AppContext from "../context/appContext";
import FileUpload from "../components/fileUpload";
import FileRenderer from "../components/fileRenderer";
import { useRouter } from 'next/router'
import Modal from 'react-modal'



export default function Home() {
  let a = { name: "abc.xlsx", size: 4044 };
  let { appState, setAppState } = useContext(AppContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" h-screen ">
        <h1>Hello</h1>
		<FileUpload />
<FileRenderer	file={a}></FileRenderer>
      </div>
    </>
  );
}
