import Head from 'next/head';
import React, { useCallback, useContext ,useEffect} from 'react';
import AppContext from '../context/appContext';
import FileUpload from '../components/fileUpload';
import FileRenderer from '../components/fileRenderer';
import AppModal from "../components/appModal"
import { getDependentsFromExt, getExtFromName, getComponentTobeRenderd } from '../lib/util';


export default function Home() {
	let a = { name: 'abc.xlsx', size: 4044 };
	let { appState, setAppState } = useContext(AppContext);

	

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className=" container mx-auto">
				<div className="text-center">
					<h1 className="font-bold font-heading text-7xl bg-primary text-white inline-block mb-1 p-2">
						Just 6 Seconds.
					</h1>
					<h2 className="text-4xl font-bold font-body">
						Simply Select your file to Convert.
					</h2>
				</div>
				<FileUpload />
				<AppModal />
				
			</div>
		</>
	);
}